### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by mybestcool** [go-pogo/sdlkit#1]
This project is very good. When I compile it,  I encountered some errors. It May missing some files

**Comment by roeldev** [comment]
Hi, thanks for your message :)
It appears I was in the middle of some refactoring and somehow did not fully complete it. I'm gonna have to take a deeper look at it... expect an update in about a week or so.

**Comment by roeldev** [comment]
I've added a lot of missing files and updated some obvious problems. Unfortunately I'm unable to test and verify that everything is working now. For now I don't have plans to further update or support this repository. Feel free to submit a PR with changes or fork the repo if you'd like.
